### PR TITLE
Update polyfills.ts - add hasOwn

### PR DESCRIPTION
**Pull request by remy**
I was able to build the project but not test it (wasn't sure how to beyond opening the index page in a browser, which didn't really do much).

Hopefully this is good to accept to give support to "old" MacOS again.

### CODE REVIEW

**Comment by neil-morrison44** [comment]
Thanks for this,

`npm run tauri dev` should get the app open in dev mode, assuming you've got Rust installed

(from [the Tauri guide](https://tauri.app/v1/guides/getting-started/setup/vite#:~:text=And%20that%27s%20it!%20Now%20you%20can%20run%20the%20following%20command%20in%20your%20terminal%20to%20start%20a%20development%20build%20of%20your%20app%3A))

**Comment by neil-morrison44** [comment]
Can ignore those errors, just GitHub secrets things.

thanks again

**Comment by remy** [comment]
Just confirming that I'm able to run the local version of pocket-sync (and this does indeed fix it).

**Comment by neil-morrison44** [comment]
👍🏻 There's a couple of things I'm looking at getting in just now, then I'm hoping to get a release out either on Sunday or sometime next week

**Pull request merged**
