### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by f00b4r0**
French translation made on inlang.

I have tried to stay consistent with the GUI context and typical French "best practices".

I have used "cœur" to translate "core" (instead of "noyau", the former being more prevalent in the French FPGA technical lingo and more relevant IMO).

Translation of the "Fetch" section turned out to be rather awkward, I might revisit later if nobody beats me to it.

Elements that are left untranslated are either the same word in French or I wasn't sure yet how to properly translate them (some technical anglicism don't really map well into French): they belong to areas of Pocket Sync I haven't explored yet so I might revisit them later as well once I get a better grasp of the implied meaning.

FWIW I have not tested the resulting translation (I'm not sure how to do that).

Disclaimer: I'm a native French (France) speaker with excellent fluency in English.

HTH

### CODE REVIEW

**Comment by neil-morrison44** [comment]
Thanks for this!

Yeah - the Chinese translation also had issues with the Fetch section.

I was about to send a link to that PR in the hopes that some of your questions would already be answered there but it's just _gone_ https://github.com/neil-morrison44/pocket-sync/pull/154 along with the user that raised it which is really weird.

Ask whatever questions you need to about it & translations for other lesser used features and I'll try to explain.

As for running it you'd need to run the whole app locally, [can follow long here](https://tauri.app/v1/guides/development/development-cycle) you'll need Rust installed etc so it's not a requirement (I'll check it doesn't crash etc before it goes out)

Thanks again

---

Also if you have feedback on the inlang thing as a contributor it'd be interesting it hear it - think you're the first person to use it (it was one of their team that added it to this repo recently)

**Comment by f00b4r0** [comment]
> Thanks for this!

yw

> Yeah - the Chinese translation also had issues with the Fetch section.
> 
> I was about to send a link to that PR in the hopes that some of your questions would already be answered there but it's just _gone_ #154 along with the user that raised it which is really weird.
> 
> Ask whatever questions you need to about it & translations for other lesser used features and I'll try to explain.

OK thanks, I'll take a closer look and will report back.

By the way on the topic of awkward text: the "connect to Pocket" button on the welcome page has a confusing label IMHO: when I first installed the software and saw that, I thought it meant I had to connect my pocket via USB-C before clicking that (I know, I'm dumb ;).

It's only when I clicked the button and realized it seemed to want to open a folder that I figured it only wanted the SD card. Might I suggest you rename it to "Open SD card" or "Open Pocket SD card". The latter will translate into a fairly long sentence in most latin languages I think (due to determiners), hence the shorter form being probably better for a button label: it's obvious it's the Pocket SD we're talking about.
 
> As for running it you'd need to run the whole app locally, [can follow long here](https://tauri.app/v1/guides/development/development-cycle) you'll need Rust installed etc so it's not a requirement (I'll check it doesn't crash etc before it goes out)

Thanks, this does look a little more involved than what I'm ready to endure :)
 
> Thanks again
> 
> Also if you have feedback on the inlang thing as a contributor it'd be interesting it hear it - think you're the first person to use it (it was one of their team that added it to this repo recently)

The interface is relatively convenient but it looses the hierarchy of the underlying JSON file (you have to really pay attention to the translation identifier to figure out which part of the UI you are translating and how it relates to other translations).

It's unclear whether leaving a TL string empty will default to the reference (English) translation (I assumed it would, since it complains about identical content - but the warning puzzled me: do we want duplicate content or is it better to leave it empty to automatically reuse the reference?), and it's also asking multiple times for the exact same translation (e.g. "Close"): ISTR gettext po files regroup multiple occurrences of the same TL string, which is more convenient and quicker.

HTH

**Comment by f00b4r0** [comment]
Hi again,

So I took another look at the Fetch thing, and I believe (again in my very humble opinion ;) that it's hard to translate because it's probably not ideally named. Looking at what it does, and correct me if I'm wrong, it does these two things:

1. *copy*(/*clone*) the (local) contents of a local folder to a destination folder (in fact there's no check on the target directory so it doesn't have to live on the SD card, I just checked that - bug or feature? :)
2. *copy*(/*clone*) the (remote) contents of a remote Internet Archive folder to a destination folder, with optional filtering on file extension.

It seems to me that "Fetch" can apply to 2 but not really to 1 (you don't typically "fetch" local files in computer lingo).

Considering this, I think it would be clearer to rename "Fetch" into either "Copy" or "Clone", possibly using the plural to further distinguish from e.g. the traditional "Copy" (from Edit menu) and emphasise that multiple copies/clones can be setup.

The "Fetch" button next to each operation can be renamed either "Copy", "Clone", "Run" or even "Execute", since here too, I think "Fetch" only properly applies to remote operations.

With all that considered the translation becomes (at least in French) quite easier and clearer.

Meanwhile I ran into a few bugs while testing this so I'll head over to the Issues section now ;)

HTH

**Comment by neil-morrison44** [comment]
> "connect to Pocket" button on the welcome page has a confusing label IMHO

USB-C connection does actually work, if you turn on the USB drive feature on the Pocket - though it's so slow it's not recommended. 

It's something I struggled with before deciding that it was fairly obvious what to do once the button was clicked, and _so far_ there's only been one user who's reported struggling with it from there, but there may well be more.

> It's unclear whether leaving a TL string empty will default to the reference (English) translation (I assumed it would, since it complains about identical content - but the warning puzzled me: do we want duplicate content or is it better to leave it empty to automatically reuse the reference?), and it's also asking multiple times for the exact same translation (e.g. "Close"): ISTR gettext po files regroup multiple occurrences of the same TL string, which is more convenient and quicker.

Yeah, I had exactly the same issue with it - they opened this feature request to track it https://github.com/opral/monorepo/discussions/2134
It _will_ default to the English and I've been using that in cases where it's more important to match what the Pocket will display things as (e.g. the names of the Display Modes) than provide a translation. I've been leaving them empty rather than have to go around changing multiple files if they need changed down the line.

> Oh and one last thing: inlang doesn't create a new branch when editing, so edits and PR are created from the repository default branch which is not ideal (for latter syncing with upstream).

Yeah, I wasn't sure what it'd do when an outside user used it, it pushes my changes direct to main when I'd probably rather branch & PR even my own stuff.

---

On the `Fetch` bit it's a shame that the PR which added the Chinese translations is mysteriously 404ing now since they had almost exactly the same comment. 

I struggled with the naming there too, before going for "Fetch" in the "go and bring this back to me here" sense - I use it to pull files off a network drive which probably makes the file system side of it more "Fetchy" for me.
Also the plan was (and is) to add more options to this similar to the Internet Archive, which would make "Fetch" make more sense.
Feel free to change this to something which covers those bases but is cleaner / clearer in the translation though


Thanks again

**Comment by f00b4r0** [comment]
> > "connect to Pocket" button on the welcome page has a confusing label IMHO
> 
> USB-C connection does actually work, if you turn on the USB drive feature on the Pocket - though it's so slow it's not recommended.
> 
> It's something I struggled with before deciding that it was fairly obvious what to do once the button was clicked,

Permission to respectfully disagree requested: a good UI shouldn't require its user to *guess* intent. A good test for this is to strap yourself in the shoes of a blind person using a screen reader: UI text must convey *all* the necessary information to use the UI.

In my case I first plugged the Pocket, clicked on the button and was greated with the open dialog. *Because I'm fairly tech savvy* I figured out what it really wanted, but I could just as well have wondered whether this was the expected result or if it meant that e.g. my Pocket was incorrectly connected. Less savvy users would be more likely to be puzzled I think.

Also consider that in fact, you can *open* any Pocket-layout folder (I just tried that): could be a local copy of the SD, a disk image, etc.

I ended up removing the French TL for this button because in French, "connect" really implies "plug in" (that's why I started there) and that would be totally confusing.

> and _so far_ there's only been one user who's reported struggling with it from there, but there may well be more.

The fact that you have now *2* users that *reported* this (most people don't bother reporting anything) suggests there is a problem. Please reconsider :)

Even "Open Pocket SD" would be clearer IMHO, since the button does bring up an *open* modal.

> > It's unclear whether leaving a TL string empty will default to the reference (English) translation (I assumed it would, since it complains about identical content - but the warning puzzled me: do we want duplicate content or is it better to leave it empty to automatically reuse the reference?), and it's also asking multiple times for the exact same translation (e.g. "Close"): ISTR gettext po files regroup multiple occurrences of the same TL string, which is more convenient and quicker.
> 
> Yeah, I had exactly the same issue with it - they opened this feature request to track it [opral/monorepo#2134](https://github.com/opral/monorepo/discussions/2134) It _will_ default to the English and I've been using that in cases where it's more important to match what the Pocket will display things as (e.g. the names of the Display Modes) than provide a translation. I've been leaving them empty rather than have to go around changing multiple files if they need changed down the line.

That makes sense. The downside is that you have no way to track how many elements are actually missing a proper TL.

> > Oh and one last thing: inlang doesn't create a new branch when editing, so edits and PR are created from the repository default branch which is not ideal (for latter syncing with upstream).
> 
> Yeah, I wasn't sure what it'd do when an outside user used it, it pushes my changes direct to main when I'd probably rather branch & PR even my own stuff.

That turned out to be really annoying: having to rebase the 'main' branch really doesn't feel right. And I can't move to another branch because it would close this PR. I hope they fix this.

Another annoyance: I couldn't figure out how to pickup my TL changes in inlang to update them. I ended up manually editing the JSON file (which carries its own risk - I'm looking at you trailing comma). Seems this tool is still a bit rough and needs more polishing.

Lastly, I think it's wrong they create two separate commit when a new language is added: the first commit adding the language is detached from the actual translation. I ended up squashing them.

> On the `Fetch` bit it's a shame that the PR which added the Chinese translations is mysteriously 404ing now since they had almost exactly the same comment.

Which suggests that here too it might be worth reconsidering the labelling, in my very humble opinion :-)

> I struggled with the naming there too, before going for "Fetch" in the "go and bring this back to me here" sense - I use it to pull files off a network drive which probably makes the file system side of it more "Fetchy" for me.

Hmm, no? A network drive attached to your computer appears to the OS as (mostly) any other drive and copying files from it is still a "copy", as further hinted by the fact that Pocket Sync will ask to open an "Origin folder" without differentiating whether it's on a network drive or local drive :)

> Also the plan was (and is) to add more options to this similar to the Internet Archive, which would make "Fetch" make more sense. Feel free to change this to something which covers those bases but is cleaner / clearer in the translation though

The problem is that if I get overly creative this will no longer be a translation. "Fetch" in French ("*récupérer*") is awkward in this context because it's seldom used in fr software. The main use case I can think of is in data *recovery* scenario.

Even the Spanish TL shows the awkwardness: they used "*buscar*"/"*búsqueda*", which in *computer context* most often means *to search* / *a search* (AIUI that's what you find in Spanish search bars -- though I'm no fluent Spanish speaker): there's bound to be some confusion for Spanish users there I believe.

Finally there's one more hint in your own code: `fetch.copying` says "*Copying Files...*" :-)

I think all this points toward using some other word. If you really don't want to consider Copy/Clone, there may be another way to look at this: what we're adding in this section are *data sources* to be replicated. Maybe *Data*, *Sources* or *Data Sources* would work? e.g. "Sources" for the menu, "Add new data source" in button / modal to be extra clear and you can just use "Add" for the modal validation button. Just thinking out loud here.

In the meantime I removed the TL strings that featured "fetch" because they really don't work in French.

Anyway, sorry for the lengthy reply, I wanted to be as clear as possible.

HTH

**Comment by neil-morrison44** [comment]
Hey - sorry about taking so long to get back to you on this, all my Pocket Sync time was put into the big refactor in https://github.com/neil-morrison44/pocket-sync/pull/247

I agree on the connect button - will change it to `"Connect to Pocket / SD Card"` for the next version, "Fetch" still makes sense to me though - particularly because it's where the functionally to download and install "Extras" will live once that gets in place

**Comment by f00b4r0** [comment]
> Hey - sorry about taking so long to get back to you on this, all my Pocket Sync time was put into the big refactor in #247

No worries :)

> I agree on the connect button - will change it to `"Connect to Pocket / SD Card"` for the next version, 

OK I'll update the TL. Nitpick: ["/" is a substitute for "or"](https://en.wikipedia.org/wiki/Slash_(punctuation)#Disjunction_and_conjunction): this now suggests there are two ways to connect :P

> "Fetch" still makes sense to me though - particularly because it's where the functionally to download and install "Extras" will live once that gets in place

Well, how about naming it "Extras" then? In fact it would make perfect sense :)
Alternatively, this section allows adding extra _files_ to the SD, so "Files" would work too.
Either of these options would be trivial to TL in any language. "Fetch" however isn't as we've seen, which suggests this naming can be confusing. In my very humble opinion a UI button should tell the user _what_ it's dealing with, now _how_ it's doing it.

HTH

**Comment by f00b4r0** [comment]
TL updated. (FWIW using inlang to update is a nightmare: it doesn't remove TL strings which have no more origin and for some reason it made my browser unbearably slow.)

**Comment by neil-morrison44** [comment]
> this now suggests there are two ways to "connect"

There _are_ two ways to connect - either plugging in the USB cable while the Pocket is set to USB drive mode, or ejecting and connecting the SD card.

With `Fetch` - that's just its name in English, like the game you can play with a dog or "Please _fetch_ me the mail?" - I really don't mind what it's called in other languages so long as it conveys roughly the same meaning & isn't more specific in a way that future additions of "getting _stuff_ from somewhere" wouldn't fit.

---

How close is this to you being comfortable having it merged? 

There'll likely be a release going out later today (assuming I don't find any other bugs), but there's no rush to be ready for that (& the refactor going out was big enough that I'm assuming there'll be bug fix releases next week)

**Comment by f00b4r0** [comment]
> > this now suggests there are two ways to "connect"
> 
> There _are_ two ways to connect - either plugging in the USB cable while the Pocket is set to USB drive mode, or ejecting and connecting the SD card.

That's not really two ways though, that's just using the Pocket as a (very slow) SD card reader and you're still _opening_ the mounted SD ;)

I can TL as is ("connecter") but don't blame me if you get bugreports from users who don't understand what is actually meant ;P

> With `Fetch` - that's just its name in English, like the game you can play with a dog or "Please _fetch_ me the mail?"

I'm aware; but this doesn't apply in French in a computer context.

> - I really don't mind what it's called in other languages so long as it conveys roughly the same meaning & isn't more specific in a way that future additions of "getting _stuff_ from somewhere" wouldn't fit.
> 
> How close is this to you being comfortable having it merged?

I'm done (save for the connect above): I think Fetch should stay as is and be its own thing, it really has no non-awkward/non-confusing TL in French that I can think of (maybe someone else will). The MiSTer strings aren't TL'd either: I don't have a MiSTer but if you can show me screenshots of the various screens so I get some context I can always add the TL later.

Cheers

**Comment by neil-morrison44** [comment]
👍🏻 here's some screenshots of the MiSTer sync bit

Screenshot 2024-02-25 at 18 11 15
Screenshot 2024-02-25 at 18 11 22
Screenshot 2024-02-25 at 18 12 01
Screenshot 2024-02-25 at 18 12 07
Screenshot 2024-02-25 at 18 12 50

(the log at the bottom comes from the Rust side so isn't translatable, yet anyway)

**Comment by f00b4r0** [comment]
done

**Comment by neil-morrison44** [comment]
👍🏻 thanks again for this

**Pull request merged**
