### PR TITLE
Fix .at polyfill to prevent blank screen

### PR DESCRIPTION
**Pull request by remy**
.at(<negative>) was failing (because the polyfill was wrong).

This fixes it.

### CODE REVIEW

**Comment by remy** [comment]
Looks like the tests fail because of a secret key missing

**Comment by remy** [comment]
Not sure what the extra commits are turning up, but it can be squashed

**Comment by neil-morrison44** [comment]
Thanks for this,

Wonder what changed - the polyfill seemed to work when it went in.

I’ll get this out with the next release alongside the display mode bits

**Comment by remy** [comment]
It was this change: https://github.com/neil-morrison44/pocket-sync/commit/25c048562ced7f254a2b0fac5c000f1e024e799f#diff-8e133c6a654c988a7f9aac2f461853a5a670df05b35e23d1ac689fd618340a2eR108

The first `at` polyfill was pretty simple, but didn't handle negatives (which I assume weren't being used). I personally tend to head to MDN (which usually takes me to core-js) for a good (battle tested) polyfill.

**Pull request merged**
