### PR TITLE
feat: add localization editor

### PR DESCRIPTION
**Pull request by NilsJacobsen**
> Hi together, let me know what I need to change in order to merge this

## Added a [localization editor](https://inlang.com/m/tdozzpar)

- Continuous i18n process improvements
- Improved translation status

### Editor -> Fink Translation Editor ([Open Editor](https://fink.inlang.com/github.com/NilsJacobsen/pocket-sync))
image

## What I added
- Added `project.inlang/settings.json` file to configure the [inlang](https://inlang.com/) project.
- `repo id` file was generated by the SDK

## All opt-in
- I didn't change you setup, everybody can use what they want (opt-in)
- It's only a config

### CODE REVIEW

**Comment by neil-morrison44** [comment]
Hi, thanks for this - I've had a play around with it and it seems really useful.

Couple of questions:

- The pricing is listed as `Free Beta` just now, is the plan that it'll always be free for public Github repos or will there be a cost introduced at some point?

- Is there any way to configure the "Missing Translation" count / filter to have it more gracefully handle things like the `en_US` file (where the `en` one is used as the default & the only translations that need done on top of that are `colour` -> `color` etc)

**Comment by NilsJacobsen** [comment]
Hi @neil-morrison44, 

great to hear that:)

> The pricing is listed as Free Beta just now, is the plan that it'll always be free for public Github repos or will there be a cost introduced at some point?

When you are not commercial, we will try to work out a free option, but we are not in the details yet:)

> Is there any way to configure the "Missing Translation" count / filter to have it more gracefully handle things like the en_US file (where the en one is used as the default & the only translations that need done on top of that are colour -> color etc)

You can only scope language lint in the [CLI](https://inlang.com/m/2qj2w8pu). I opened a [feature request](https://github.com/opral/monorepo/discussions/2134) for you. In the meanwhile you can try to machine translate the`en-US` with the CLI and then work on that base.

**Comment by neil-morrison44** [comment]
I think that having a small `en_US` file that just has the differences from the `en` file probably makes sense here - fewer places to update if a translation needs changes & avoids the duplicated translation warning.

**Comment by NilsJacobsen** [comment]
I agree. There need to be some local override for fink to give the lint rule a languageTag scope.

**Pull request merged**
